DIProject/Controllers/DIPController.cs
using System;
using System.Drawing;
using System.Net;
using System.Web.Mvc;
using DIProject.Helpers;
using DIProject.Models;
using DIProject.Services;

namespace DIProject.Controllers
{
    public class DIPController : Controller
    {
        private static Image _image;

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.type = "setpixels";
            return View();
        }

        [HttpPost]
        public ActionResult Upload()
        {
            if (Request.Files.Count > 0)
            {
                foreach (string fil in Request.Files)
                {
                    var httpPostedFileBase = Request.Files[fil];
                    if (httpPostedFileBase != null)
                        _image = Image.FromStream(httpPostedFileBase.InputStream, true, true);
                }
                var imageBytes = ImageHelper.ImageToByteArray(_image);
                return Content(ImageHelper.ImageBytesToBase64(imageBytes));
            }
            return new HttpStatusCodeResult(HttpStatusCode.NotFound);
        }

        [HttpPost]
        public ActionResult Invert()
        {
            return ReturnBitmap(ImageProcessingService.Invert((Bitmap)_image), false);
        }

        [HttpPost]
        public ActionResult SetGrayscale()
        {
            return ReturnBitmap(ImageProcessingService.SetGrayscale((Bitmap)_image), false);
        }

        [HttpPost]
        public ActionResult SetBrightness(int brightness)
        {
            return ReturnBitmap(ImageProcessingService.SetBrightness((Bitmap)_image, brightness), false);
        }

        [HttpPost]
        public ActionResult SetColorFilter(string colorFilter)
        {
            ColorFilterTypes colorFilterType;
            Enum.TryParse(colorFilter, true, out colorFilterType);
            return colorFilterType == ColorFilterTypes.None ? Content(ImageHelper.ImageBytesToBase64(ImageHelper.ImageToByteArray(_image))) : ReturnBitmap(ImageProcessingService.SetColorFilter((Bitmap)_image, colorFilterType), false);
        }

        [HttpPost]
        public ActionResult SetContrast(int contrast)
        {
            return ReturnBitmap(ImageProcessingService.SetContrast((Bitmap)_image, Convert.ToDouble(contrast)), false);
        }

        [HttpPost]
        public ActionResult Resize(int newWidth, int newHeight)
        {
            return ReturnBitmap(ImageProcessingService.Resize((Bitmap)_image, newWidth, newHeight), false);
        }

        [HttpPost]
        public ActionResult RotateFlip(string rotateFlip)
        {
            RotateFlipType rotateFlipType;
            Enum.TryParse(rotateFlip, true, out rotateFlipType);
            return ReturnBitmap(ImageProcessingService.RotateFlip((Bitmap)_image, rotateFlipType), false);
        }

        private ContentResult ReturnBitmap(Image bitmap, bool overrideCurrentImage)
        {
            if (overrideCurrentImage)
                _image = bitmap;
            var imageBytes = ImageHelper.ImageToByteArray(bitmap);
            var base64 = ImageHelper.ImageBytesToBase64(imageBytes);
            return Content(base64);
        }


    }
}

DIProject/Controllers/DIPLockBitsController.cs
using System;
using System.Drawing;
using System.Net;
using System.Web.Mvc;
using DIProject.Helpers;
using DIProject.Services;

namespace DIProject.Controllers
{
    public class DIPLockBitsController : Controller
    {
        private static Image _image;

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.type = "lockbits";
            return View();
        }

        [HttpPost]
        public ActionResult Upload()
        {
            if (Request.Files.Count > 0)
            {
                foreach (string fil in Request.Files)
                {
                    var httpPostedFileBase = Request.Files[fil];
                    if (httpPostedFileBase != null)
                        _image = Image.FromStream(httpPostedFileBase.InputStream, true, true);
                }
                var imageBytes = ImageHelper.ImageToByteArray(_image);
                return Content(ImageHelper.ImageBytesToBase64(imageBytes));
            }
            return new HttpStatusCodeResult(HttpStatusCode.NotFound);
        }

        [HttpPost]
        public ActionResult Invert()
        {
            return ReturnBitmap(ImageProcessingWithBitLocksService.Invert((Bitmap)_image));
        }

        [HttpPost]
        public ActionResult SetGrayscale()
        {
            return ReturnBitmap(ImageProcessingWithBitLocksService.SetGrayscale((Bitmap)_image));
        }

        [HttpPost]
        public ActionResult SetBrightness(int brightness)
        {
            return ReturnBitmap(ImageProcessingWithBitLocksService.SetBrightness((Bitmap)_image, brightness),false);
        }

        [HttpPost]
        public ActionResult SetContrast(int contrast)
        {
            return ReturnBitmap(ImageProcessingWithBitLocksService.SetContrast((Bitmap)_image, Convert.ToDouble(contrast)),false);
        }

        [HttpPost]
        public ActionResult Resize(int newWidth, int newHeight)
        {
            return ReturnBitmap(ImageProcessingWithBitLocksService.Resize((Bitmap)_image, newWidth, newHeight));
        }

        [HttpPost]
        public ActionResult RotateFlip(string rotateFlip)
        {
            RotateFlipType rotateFlipType;
            Enum.TryParse(rotateFlip, true, out rotateFlipType);
            return ReturnBitmap(ImageProcessingService.RotateFlip((Bitmap)_image, rotateFlipType));
        }

        [HttpPost]
        public ActionResult HorizontalFlip()
        {
            return ReturnBitmap(ImageProcessingWithBitLocksService.HorizontalFlip((Bitmap)_image));
        }

        [HttpPost]
        public ActionResult EdgeDetection()
        {
            return ReturnBitmap(ImageProcessingWithBitLocksService.EdgeDetection((Bitmap)_image));
        }

        [HttpPost]
        public ActionResult GaussianBlur()
        {
            return ReturnBitmap(ImageProcessingWithBitLocksService.GaussianBlur((Bitmap)_image));
        }

        public ActionResult HistEq()
        {
            return ReturnBitmap(ImageProcessingWithBitLocksService.HistEq((Bitmap)_image));
        }

        private ContentResult ReturnBitmap(Image bitmap, bool overrideCurrentImage = true)
        {
            if (overrideCurrentImage)
                _image = bitmap;
            var imageBytes = ImageHelper.ImageToByteArray(bitmap);
            var base64 = ImageHelper.ImageBytesToBase64(imageBytes);
            return Content(base64);
        }
    }
}

DIProject/Views/Shared/Index.cshtml
@{
    ViewBag.Title = "DIProject";
}

<input type="hidden" id="type" value="@ViewBag.type" />

<form action="" method="post" enctype="multipart/form-data">
    <input type="file" name="file" id="file" />
    <input type="button" name="submit" id="upload" value="Załaduj" />
</form>

<div class="imageHolder">
    <img id="img" alt="Nie wybrano pliku" />
    <hr/>
    <br/>

    <label for="currentHeight">Wysokość</label>
    <p id="currentHeight">-</p>
    <label for="currentWidth">Szerokość</label>
    <p id="currentWidth">-</p>
</div>
<hr />

<div class="tools">
    <input type="button" name="invert" id="invert" value="Odwróć kolory" />
    <input type="button" name="grayscale" id="grayscale" value="Skala szarości" />
    <input type="button" name="edges" id="edges" value="Wykryj krawędzie" />
    <input type="button" name="blur" id="blur" value="Rozmycie gaussowskie" />
    <input type="button" name="hist" id="hist" value="Wyrównanie histogramu" />
    <br />
    <label for="brightness">Jasność</label>
    <input type="range" name="brightness" id="brightness" min="-255" max="255" step="15" />

    <br />
    <label for="contrast">Kontrast</label>
    <input type="range" name="contrast" id="contrast" min="-100" max="100" step="10" />

    <button id="Rotate90FlipNone" class="rotate">Obrót w prawo</button>
    <button id="Rotate270FlipNone" class="rotate">Obrót w lewo</button>
    <button id="Rotate180FlipNone" class="rotate">Obrót o 180 stopni</button>
    <button id="flip" class="rotate">Odbicie lustrzane</button>

    <div name="resize">


        <input type="number" min="1" name="width" id="width" placeholder="szerokość" />
        <input type="number" min="1" name="height" id="height" placeholder="wysokość" />
        <input type="button" id="resizeButton" value="Zmień rozmiar" />
    </div>
</div>

<h1><time>00:00:00.000</time></h1>

DIProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Digital Image Processing Project</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">DIProject</a>
            </div>
            <ul class="nav navbar-nav">
                @*<li><a href="@Url.Action("Index","DIP")">Get/SetPixels</a></li>*@
                <li><a href="@Url.Action("Index", "DIPLockBits")">CLICK HERE!!1</a></li>
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="jumbotron">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/script")
    @RenderSection("scripts", required: false)
</body>
</html>